name: "构建 Docker 并上传"

inputs:
  dockerhub-user:
    required: false
    default: ""
  dockerhub-token:
    required: false
    default: ""
  push:
    required: false
    default: "false"
  platforms:
    required: false
    default: "linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"
  image-name:
    required: false
    default: "halo"

runs:
  using: "composite"
  steps:
    - name: Halo 的 Docker 元
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          mutouloves/${{ inputs.image-name }}
        tags: |
          type=semver,pattern=latest
          type=semver,pattern={{ version }}
        flavor: |
          latest=false
          
    - name: 建虚拟机
      uses: docker/setup-qemu-action@v3
      
    - name: 设置构建
      uses: docker/setup-buildx-action@v3
      
    - name: 登陆 Docker Hub
      if: inputs.dockerhub-token != '' && github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-token }}
        
    - name: 构建镜像并上传
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ inputs.platforms }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ (inputs.dockerhub-token != '') && inputs.push == 'true' }}
