name: Manual # 手动触发

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 核对仓库
        uses: actions/checkout@v4
      
      - name: 安装环境
        uses: ./.github/actions/setup-env
        
      - name: 重置 Halo 版本
        if: github.event_name == 'release'
        shell: bash
        run: |
          # Set the version with tag name when releasing
          version=${{ github.event.release.tag_name }}
          version=${version#v}
          sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
          
      - name: 构建 Halo
        run: ./gradlew clean && ./gradlew downloadPluginPresets && ./gradlew build -x check
        
      - name: 上传工件
        uses: actions/upload-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
          retention-days: 1

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 核对仓库
        uses: actions/checkout@v4
      
      - name: 下载工件
        uses: actions/download-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
          
      - name: 构建 Docker 并上传
        uses: ./.github/actions/docker-buildx-push
        with:
          image-name: halo
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub-token: ${{ secrets.DOCKERHUB_PASS }}
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
