name: Manual # 手动触发

on:
  workflow_dispatch:  # 手动触发

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: 核对仓库 
        uses: actions/checkout@v4
      - name: 下载队列
        uses: actions/download-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
      - name: 确定 Docker 标签
        id: vars
        shell: bash
        run: |
          # 由 github.ref 确定我们要构建的标签
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "DOCKER_TAG=${GITHUB_REF#refs/*/}" | tee -a "${GITHUB_OUTPUT}"
          elif [[ "${{ github.ref }}" == refs/heads/* ]]; then
            echo "DOCKER_TAG=1.0" | tee -a "${GITHUB_OUTPUT}"
          fi
      - name: 构建镜像并上传
        uses: ./.github/actions/docker-buildx-push
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub-token: ${{ secrets.DOCKERHUB_PASS }}
          push: true
          tags: |
            mutouloves/halo:latest
            mutouloves/halo:${{steps.vars.outputs.DOCKER_TAG}}
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
